//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RemoteControl.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LANController
    {
        public LANController()
        {
            this.Camera = new HashSet<Camera>();
            this.Buttons = new HashSet<Button>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string ControllerPath { get; set; }
        public string UserManager { get; set; }
        public string UserOwner { get; set; }
        public bool IsPublic { get; set; }
        public bool IsWork { get; set; }
    
        public virtual ICollection<Camera> Camera { get; set; }
        public virtual ICollection<Button> Buttons { get; set; }
    }
}
