//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RemoteControl.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Queue
    {
        public int Id { get; set; }
        public string UserName { get; set; }
        public Nullable<int> CameraId { get; set; }
    
        public virtual Camera Camera { get; set; }
    }
}
