//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RemoteControl.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserCamera
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> StartUse { get; set; }
        public Nullable<System.DateTime> EndUse { get; set; }
        public Nullable<System.TimeSpan> CommonTimeUse { get; set; }
        public string UserId { get; set; }
        public int CameraId { get; set; }
        public string UserName { get; set; }
    
        public virtual Camera Camera { get; set; }
    }
}
