//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace AbstractFactory
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public abstract class AbstractFactory
	{
		public virtual AbstractProduct_A CreateProductA()
		{
			throw new System.NotImplementedException();
		}

		public virtual AbstractProduct_B CreateProductB()
		{
			throw new System.NotImplementedException();
		}

	}
}

