//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace AbstractFactory
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class Factory_B : AbstractFactory
	{
       
        public override AbstractProduct_A CreateProductA()
        {
            return new Product_A1();
        }
        public override AbstractProduct_B CreateProductB()
        {
            return new Product_B1();
        }
	}
}

